### ISSUE TITLE
Привести входные данные к типу int, исправить опечатки

### ISSUE THREAD

**Issue by coursar** [protpolymer/cashback#3]
https://github.com/protpolymer/cashback/blob/51fa3190d70d20ece355a222e290d33b1c25a576/src/main/java/ru/itpark/CashbackService.java#L4

Если нужен double - приводите к нему внутри метода

**Comment by protpolymer** [comment]
Предполагалось, что покупка может иметь не только целочисленную цену. По условиям выплаты кэшбэка нет необходимости в числах с плавающей точкой. Исправлено
