### ISSUE TITLE
Условие не покрыто авто-тестами

### ISSUE THREAD

**Issue by coursar** [protpolymer/cashback#4]
https://github.com/protpolymer/cashback/blob/51fa3190d70d20ece355a222e290d33b1c25a576/src/main/java/ru/itpark/CashbackService.java#L13-L15

**Comment by protpolymer** [comment]
Добавлены автотесты на нулевые суммы покупок по всем категориям, по каждой в отдельности и по максимальному получаемому кэшбэку
