### ISSUE TITLE
Приведение к int теперь избыточно

### ISSUE THREAD

**Issue by coursar** [protpolymer/cashback#6]
https://github.com/protpolymer/cashback/blob/ea567736429d3eb2d8a4b31e001328c957bcfa90/src/main/java/ru/itpark/CashbackService.java#L11

**Comment by protpolymer** [comment]
Исправлено
23c9286ecd1f1a7413d5ced0eb04fcdbe26d914d
72e6c45602ffe3f4ef8b2f2dfcf97b2620dbaa86
