### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by protpolymer** [protpolymer/cashback#7]
Я добавил pom файл, который вы использовали в лекции.
Теперь у меня сборку обрывает плагин jacoco, потому что нет тестов на класс Main (Я не знаю как писать тест на этот класс).
Если поставить минимальный предел покрытия в 0%, то падает другая ошибка из-за плагина maven-pmd-plugin, который выдает:
`Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.11.0:check (default)`

Что именно мне надо сделать для исправления? аналогичная проблема на остальных работах

**Comment by coursar** [comment]
Что пишет PMD?

**Comment by protpolymer** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.8.0" timestamp="2018-12-12T16:39:03.082">
<file name="C:\Users\n.savin\IdeaProjects\Cashback\src\main\java\ru\itpark\CashbackService.java">
<violation beginline="11" endline="11" begincolumn="24" endcolumn="59" rule="UselessParentheses" ruleset="Code Style" package="ru.itpark" class="CashbackService" method="cashbackCalculate" externalInfoUrl="https://pmd.github.io/pmd-6.8.0/pmd_rules_java_codestyle.html#uselessparentheses" priority="4">
Useless parentheses.
</violation>
</file>
</pmd>

```

**Comment by protpolymer** [comment]
ок, ругается на количество скобок. Поправил, верификацию проходит.
А что делать с покрытием кода? как тестировать класс main?

**Comment by protpolymer** [comment]
Можно просто удалить этот класс?

**Comment by coursar** [comment]
Отключите JaCoCo, либо уберите check, который обваливает сборку.
